# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBufTaskGraph

class SimTaskType(object):
    TASK_FORWARD = 0
    TASK_BACKWARD = 1
    TASK_COMM = 2
    TASK_UPDATE = 3
    TASK_BARRIER = 4
    TASK_NOMINAL_COMM = 5
    TASK_ALLREDUCE = 6
