#!/bin/bash
#SBATCH --account=jpwalter_148
#SBATCH --partition=largemem
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=512GB
#SBATCH --time=12:00:00

module purge
module load gcc/11.3

FF_HOME=/project/jpwalter_148/imes/STEAM-FlexFlow

${FF_HOME}/ffsim-opera/src/clos/datacenter/htsim_tcp_fattree -simtime 7200.1 -ssthresh 10000 -rttnet 1000 -rttrack 1000 -q 10000  -flowfile model_a_1024.tg -ofile ./model_a_1024_htsim_output -speed 100000 -nodes 1024
