# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBufTaskGraph

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Connection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Connection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConnection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Connection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Connection
    def Fromnode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Connection
    def Tonode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Connection
    def Nconn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(3)
def ConnectionStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddFromnode(builder, fromnode): builder.PrependUint32Slot(0, fromnode, 0)
def ConnectionAddFromnode(builder, fromnode):
    """This method is deprecated. Please switch to AddFromnode."""
    return AddFromnode(builder, fromnode)
def AddTonode(builder, tonode): builder.PrependUint32Slot(1, tonode, 0)
def ConnectionAddTonode(builder, tonode):
    """This method is deprecated. Please switch to AddTonode."""
    return AddTonode(builder, tonode)
def AddNconn(builder, nconn): builder.PrependUint32Slot(2, nconn, 0)
def ConnectionAddNconn(builder, nconn):
    """This method is deprecated. Please switch to AddNconn."""
    return AddNconn(builder, nconn)
def End(builder): return builder.EndObject()
def ConnectionEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)